### ISSUE TITLE
After upgrade from SFOS 3.2 to 3.3 it doesnt work anymore

### ISSUE THREAD

**Issue by HoSnoopy** [noonien-d/share-plugin-telepathy#1]
After I upgraded to Sailfish OS 3.3 the share plugin doesnt work anymore. 
I removed my jabber-account and made a new one:

[root@telefix /]# mc-tool update gabble/jabber_23 bool:force-httpupload=true
mc-tool update: Account path '/org/freedesktop/Telepathy/Account/gabble/jabber_23' is malformed: should have 3 trailing components, not 2

In Google you cannot find anything.

**Comment by noonien-d** [comment]
Your account name seems incorrect, please use `mc-tool list` to get the correct one.

**Comment by HoSnoopy** [comment]
[root@telefix /]# mc-tool list
gabble/jabber/jabber_23
ring/tel/ril_0

**Comment by noonien-d** [comment]
So its  gabble/jabber/jabber_23 instead of gabble/jabber_23 ;-)

**Comment by HoSnoopy** [comment]
Shell: [root@telefix nemo]# mc-tool update gabble/jabber/jabber_23 bool:force-httpupload=true
To apply changes to these parameters:
  force-httpupload
run:
  mc-tool reconnect gabble/jabber/jabber_23
[root@telefix nemo]#  mc-tool reconnect gabble/jabber/jabber_23

But now I cannot share at all. I press in the gallery the 3 dots for sharing and after I get nothing except the return-dot in the upper left corner. :/ Same out of the filemanager.

**Comment by HoSnoopy** [comment]
I have 3 SFOS-Devices: 2 of them have your package, 1 not. The device without still can share, the others not. Any Idea except re-installing SFOS at all?

**Comment by noonien-d** [comment]
Do you use the current version 0.4-1?

Before reinstalling Sailfish, you can to remove the packet with `pkcon remove share-plugin-telepathy`.

**Comment by noonien-d** [comment]
To get some error message, you might want to start jolla-gallery from within a terminal.

**Comment by HoSnoopy** [comment]
Okay, the tip with terminal-lauching was quite good and I think the problem is in the transfer-engine. It launches not correctly after boot. After launching in the terminal all works. Also your package. 
=> https://github.com/monich/sailfish-qrshare/issues/13 
So I think it has nothing to do with your package.

**Comment by HoSnoopy** [comment]
AH! Now I found it! 
https://together.jolla.com/question/226721/nemo-transfer-engine-is-crashing-sfos-33016/
(If somebody is looking for the same solution....)

Thanks for your fast replies!!
